# build.spec
# PyInstaller 打包配置文件

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/core', 'src/core'),
        ('src/gui', 'src/gui'),
        ('src/utils', 'src/utils'),
        ('resources', 'resources'),
        ('alias.txt', '.'),
        ('blacklist.txt', '.'),
        ('demo.txt', '.'),
    ],
    hiddenimports=[
        'src.core',
        'src.core.config',
        'src.core.run',
        'src.core.fetcher',
        'src.core.parser',
        'src.core.speed_tester',
        'src.core.ffmpeg_validator',
        'src.core.merger',
        'src.core.generator',
        'src.core.demo_filter',
        'src.core.classifier',
        'src.core.blacklist_filter',
        'src.core.database',
        'src.core.logger',
        'src.core.alias_matcher',
        'src.core.fixed_sources',
        'src.core.stable',
        'src.core.stable.manager',
        'src.core.source_pool',
        'src.core.source_pool.discoverer',
        'src.core.candidate',
        'src.core.candidate.observer',
        'src.core.quality',
        'src.core.quality.monitor',
        'src.core.iptv_org_adapter',
        'src.core.global_channels',
        'src.core.generator_enhanced',
        'src.core.overseas_filter',
        'src.core.special_categories',
        'src.core.orchestrator',
        'src.gui',
        'src.gui.main_window',
        'src.gui.widgets',
        'src.gui.styles',
        'src.utils',
        'src.utils.logger_handler',
        'pypinyin',
        'pypinyin.core',
        'pypinyin.style',
        'aiohttp',
        'aiosqlite',
        'tqdm',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='IPTV_Manager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # 显示控制台窗口，方便查看日志
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/icon.ico' if sys.platform == 'win32' else None,
)
